### ISSUE TITLE
glfw on MacOSX and Linux

### ISSUE THREAD

**Issue by Groovounet** [g-truc/ogl-samples#47]
Oï! Dans ogl-samples-4.5.0.0 il faut enlever le fichier external/glfw-3.0.3/src/config.h pour faire une build mac/linux

**Comment by elmindreda** [comment]
In GLFW 3.0.4 this file has been renamed to the more conflict-free `glfw_config.h`, which may help.

**Comment by Groovounet** [comment]
v 4.5.2 rely on GLFW 3.1.1 which should resolve this issue
