### ISSUE TITLE
gl-410-program-binary is half broken due to OGL_SAMPLES_BINARY_DIR inconsistency

### ISSUE THREAD

**Issue by jrfonseca** [g-truc/ogl-samples#48]
It tries to write the binaries to `ogl-samples/gl-410/*` instead of `ogl-samples/data/gl-410/*`:

    $ strace build/Debug/gl-410-program-binary |& grep 'binary\.\w\+\.bin' | github-quote 
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.vert.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.geom.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.frag.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.vert.bin", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.geom.bin", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.frag.bin", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.vert.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.geom.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.frag.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.vert.bin", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.geom.bin", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
    open("/home/jfonseca/work/vmware/tests/ogl-samples/gl-410/binary.frag.bin", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)

And as consequence, `glProgramBinary` call never gets exercised.  I noticed this because I wanted to test out apitrace with it.

This used to work in the past, as I can still find some old shader binaries from Feb 26  2014.
 
So it might be worth adding some additional checks when writing the binary programs to ensure this doesn't silently fail in the future too.

**Comment by jrfonseca** [comment]
> This used to work in the past, as I can still find some old shader binaries from Feb 26 2014.

Forget this paragraph -- these binaries are actually checked in the git repos.

My other comments hold true though.

**Comment by Groovounet** [comment]
This issue fixed in master branch. 

Thanks for reporting,
Christophe
