### ISSUE TITLE
Extensions.KHR_debug

### ISSUE THREAD

**Issue by elect86** [g-truc/ogl-samples#52]
Salut Christophe,

I see in the `caps::initVersion()` you check also about the `KHR_debug` extension

`if(this->check(4, 3) || Extensions.KHR_debug)`

but this extension will be checked only in the `caps::initExtensions()` which is being called after the `caps::initVersion()` in the caps constructor

Am I wrong?

**Comment by Groovounet** [comment]
Thanks for contributing,
Christophe
