### ISSUE TITLE
ARB_robustness_isolation

### ISSUE THREAD

**Issue by elect86** [g-truc/ogl-samples#54]
Double

`else if(!strcmp("GL_ARB_robustness_isolation", Extension))
				ExtensionData.ARB_robustness_isolation = true;
			else if(!strcmp("GL_ARB_robustness_isolation", Extension))
				ExtensionData.ARB_robustness_isolation = true;`

Ps: sorry but I can't push at the moment

**Comment by elect86** [comment]
Also 

`if(!strcmp("GL_EXT_texture_compression_s3tc", Extension)) {
				ExtensionData.EXT_texture_compression_s3tc = true;
				continue;
			}`

is double

**Comment by Groovounet** [comment]
Fixed.
