### ISSUE TITLE
regarding the linux instructions: sudo make x11-dist-install

### ISSUE THREAD

**Issue by LaughingSun** [g-truc/ogl-samples#59]
I tried: 
    sudo make x11-dist-install
from the ..../ogl-samples/external/glfw-3.1.1 and the ..../ogl-samples directory and also greped through the various makefiles and the is not rule for x11-dist-install.  

Could it be your readme.md is outdated? Or is something missing?

Thanks

**Comment by Groovounet** [comment]
This looks like a GLFW bug, not the samples...

Thanks,
Christophe

**Comment by elect86** [comment]
Same problems

News on this?

**Comment by elect86** [comment]
Solved by [upgrading](https://stackoverflow.com/a/49596063/1047713) to 3.2.1
