### ISSUE TITLE
gl-440-buffer-storage mapping bug

### ISSUE THREAD

**Issue by ratchetfreak** [g-truc/ogl-samples#70]
On cleanup you test if UniformPointer is not valid and if so you unmap the pointer. 

The negation should probably be removed.

https://github.com/g-truc/ogl-samples/blob/master/tests/gl-440-buffer-storage.cpp#L225-L230

**Comment by Groovounet** [comment]
This issue has been fixed in the master branch.

Thanks for contributing,
Christophe
