### ISSUE TITLE
Multi draw indirect from multiple VBOs

### ISSUE THREAD

**Issue by elect86** [g-truc/ogl-samples#71]
So, following [this](https://twitter.com/g_truc/status/704372444656738305?cn=cmVwbHk%3D&refsrc=email) conversation, I open this ticket here  :grimacing:

I asked you since you usually are one of the contributors 

I have opened also a thread on the [opengl forums](https://www.opengl.org/discussion_boards/showthread.php/198252-Multi-Draw-Indirect-from-multiple-VBOs?p=1281685#post1281685) if this may interest you

**Comment by Groovounet** [comment]
Ahhh, this is quite an OpenGL feature here actually.

Well, it' actually more effective to merge all the VBOs into a single set of array and element array buffer.

We can use BaseVertex and BaseInstance to select the right range of vertex data.

Thanks,
Christophe
