### ISSUE TITLE
gl-320-glsl-input-struct

### ISSUE THREAD

**Issue by chomicz-m** [g-truc/ogl-samples#72]
I've found an issue  in vertex shader of gl-320-glsl-input-struct test, which cause shader compilation failure on Intel OpenGL driver.
https://github.com/g-truc/ogl-samples/blob/master/data/gl-320/glsl-input-struct.vert#L18
There vertex shader use struct type for input attribute,  with contradition to [ GLSL spec](https://www.opengl.org/registry/doc/GLSLangSpec.1.50.09.pdf):

"Vertex shader inputs can only be float, floating-point
vectors, matrices, signed and unsigned integers and integer vectors. Vertex shader inputs can also form arrays of these types, but not structures"

Can you look closer into this issue ?

**Comment by scyganINTEL** [comment]
CC @scyganINTEL

**Comment by Groovounet** [comment]
Not an actual bug. The purpose of this sample is to highlight an non-conformant NVIDIA drivers behavior. The sample should fail, it's a negative test. 

I am hoping at some point to better identify negative test... I haven't had the time so far...

Thanks,
Christophe
