### ISSUE TITLE
gl-430-perf-monitor-amd, shader paths

### ISSUE THREAD

**Issue by chomicz-m** [g-truc/ogl-samples#73]
It looks like the test gl-430-perf-monitor-amd use invalid path to shader files:
https://github.com/g-truc/ogl-samples/blob/master/tests/gl-430-perf-monitor-amd.cpp#L28

**Comment by scyganINTEL** [comment]
CC @scyganINTEL

**Comment by Groovounet** [comment]
This issue has been fixed.

Thanks for contributing,
Christophe
